### ISSUE TITLE
Is that package paid somehow?

### ISSUE THREAD

**Issue by vitorleonel** [xulihang/vision-camera-dynamsoft-barcode-reader#10]
Hey,

I saw that you have a paid product (https://www.dynamsoft.com/barcode-reader/overview/) so I would like to know what are the differences between these two solutions, please.

I also saw the DBRConfig interface then I had this doubt.

![image](https://user-images.githubusercontent.com/15618005/201132361-0bd3b7a3-f0d5-4f2c-b645-51b50d691d23.png)

Thank you in advance.

**Comment by xulihang** [comment]
What is the other option you are referring to? Is it this one: https://github.com/rodgomesc/vision-camera-code-scanner? 

The Dynamsoft plugin is more flexible and robust. It supports more barcode formats than ML Kit. You can also get customer support for your own use case.

**Comment by xulihang** [comment]
I may just misunderstand your question. The plugin uses Dynamsoft Barcode Reader so it is paid.

You have to set up a license in the `DBRConfig` to use it. [License application page](https://www.dynamsoft.com/customer/license/trialLicense/?product=dbr)

**Comment by vitorleonel** [comment]
> 

You got my doubt right. Thank you for your clarification. I'll take a look in the license page.
