### ISSUE TITLE
Can this read QR code pictures from the album

### ISSUE THREAD

**Issue by Yunnathai** [xulihang/vision-camera-dynamsoft-barcode-reader#12]
Can this read QR code pictures from the album like base64

**Comment by tony-xlh** [comment]
It is possible since a frame processor plugin is basiccaly a react native native module. I just have to add a method for this.

**Comment by Yunnathai** [comment]
I'm excited about this. I can't wait. Thank you for your work.

**Comment by xulihang** [comment]
A `decodeBase64` function is added in 0.6.0.
