### ISSUE TITLE
Vision Camera V3 support 

### ISSUE THREAD

**Issue by niStee** [xulihang/vision-camera-dynamsoft-barcode-reader#15]
An update that removes the reanimated dependency and supports worklets-core would be most welcome.

**Comment by xulihang** [comment]
This is on my plan. I will try to upgrade the plugins soon.

**Comment by xulihang** [comment]
V3 is just released and has bugs. The progress is stuck.

I've opened several issues:

* https://github.com/mrousavy/react-native-vision-camera/issues/1778
* https://github.com/mrousavy/react-native-vision-camera/issues/1774

**Comment by ArturoTorresMartinez** [comment]
Much appreciated @xulihang Hope the recent push on 3.1.0 helped out the progress

**Comment by alex-benoit** [comment]
Good luck @xulihang we appreciate your time and effort maintaining this!

**Comment by tgreco** [comment]
@xulihang same question for this repo, do you have an ETA on when it will work with v3? If not would you like some help? I can try to put in a PR to make it work.

**Comment by xulihang** [comment]
I got stuck running Android at this issue: https://github.com/mrousavy/react-native-vision-camera/issues/2066 I will try to build it on Mac to try again. PRs are welcome. V3's code lies in the vision-camera-v3 branch.

**Comment by xulihang** [comment]
I've made the plugin work with v3 on Android: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/tree/vision-camera-v3-new

As for iOS, it is possible to read barcodes from an image. Since I cannot find a way to register the frame processor in Swift, I may have to rewrite the code in Objective-C to make the live scanning work.

**Comment by xulihang** [comment]
Version 1.0.0 of the plugin is now compatible with vision camera v3.
