### ISSUE TITLE
Can't find variable __decode 

### ISSUE THREAD

**Issue by diegopeixoto** [xulihang/vision-camera-dynamsoft-barcode-reader#16]
Still same error.

RN 0.70
Reanimeted 3.5.4.
RN Vision 2.16.2
Dynam 0.6.3

_Originally posted by @diegopeixoto in https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/issues/11#issuecomment-1751211561_

**Comment by tony-xlh** [comment]
Could you upload a sample project?
