### ISSUE TITLE
Installing DynamsoftBarcodeReader (9.0.0) 

### ISSUE THREAD

**Issue by yaogengzhu** [xulihang/vision-camera-dynamsoft-barcode-reader#3]
Installing DynamsoftBarcodeReader (9.0.0) 

This dependency cannot be downloaded

**Comment by xulihang** [comment]
Are you installing for iOS?

**Comment by yaogengzhu** [comment]
> Are you installing for iOS?

yeah! 


```bash
Installing DynamsoftBarcodeReader (9.0.0)
```
Long time no response

**Comment by yaogengzhu** [comment]
Thank you for your reply. It may be a network problem, and it was successfully downloaded at a certain moment @xulihang
