### ISSUE TITLE
QR Scanner is working on Android but not on iOS

### ISSUE THREAD

**Issue by luismiguelmena** [xulihang/vision-camera-dynamsoft-barcode-reader#4]
The Qr scanner is working on Android but not on iOS, im not getting any error and the camera is opening correctly

**Comment by xulihang** [comment]
Closed as you've posted it in a new issue: https://github.com/mrousavy/react-native-vision-camera/issues/1050

**Comment by dhananjay-soneji** [comment]
The Barcode scanner to scan PDF417 works on Android but not iOS; no errors, and the camera is opening correctly on both platforms.

```
"react-native-reanimated": "^2.9.1",
"react-native-vision-camera": "^2.14.0",
"vision-camera-dynamsoft-barcode-reader": "^0.4.3",
```
