### ISSUE TITLE
Attention(exceptionCode:-20111)

### ISSUE THREAD

**Issue by Vladislava9009** [xulihang/vision-camera-dynamsoft-barcode-reader#5]
When I try to use this library I got not full barcodeText.  "barcodeText": "[Attention(exceptionCode:-20111)] S**3000*25"

"vision-camera-dynamsoft-barcode-reader": "^0.4.3",
   "react-native-vision-camera": "^2.13.0",

**Comment by xulihang** [comment]
This code means the license has expired. The default public trial is only valid for one day. You can apply for your own trial license here: https://www.dynamsoft.com/customer/license/trialLicense/?product=dbr
