### ISSUE TITLE
The QR scanner is working on Android but not on iOS

### ISSUE THREAD

**Issue by dhananjay-soneji** [xulihang/vision-camera-dynamsoft-barcode-reader#6]
The Barcode scanner to scan PDF417 works on Android but not iOS; no errors, and the camera is opening correctly on both platforms.

```
"react-native-reanimated": "^2.9.1",
"react-native-vision-camera": "^2.14.0",
"vision-camera-dynamsoft-barcode-reader": "^0.4.3",
```

**Comment by xulihang** [comment]
Do not copy existing issues. https://github.com/xulihang/vision-camera-dynamsoft-barcode-reader/issues/4
