### ISSUE TITLE
Build fail on iOS Simulator on M1

### ISSUE THREAD

**Issue by Nass30** [xulihang/vision-camera-dynamsoft-barcode-reader#7]
Hello,

Works perfectly on Android + iOS Devices, but when building the app on iOS Simulator, the build fails.

```
"react-native-vision-camera": "^2.14.1",
"vision-camera-dynamsoft-barcode-reader": "^0.4.3",
"react": "18.0.0",
"react-native": "0.69.3"
```
Build error: building for iOS Simulator, but linking in dylib built for iOS, file '.../ios/Pods/DynamsoftBarcodeReader/DynamsoftBarcodeReader.framework/DynamsoftBarcodeReader' for architecture arm64

Tried to rm Pods, pod install, clean Xcode build, delete Derived Data, but still have the issue.

I couldn't try to build on the example app, the build fails but for other reasons

**Comment by Nass30** [comment]
I did some research and found this [https://developer.apple.com/forums/thread/658424](https://developer.apple.com/forums/thread/658424) and this [https://developer.apple.com/forums/thread/657913](https://developer.apple.com/forums/thread/657913) but didn't work when changing it in the pod settings

**Comment by xulihang** [comment]
You can try to use a local xcframework.

You may have to [download](https://www.dynamsoft.com/barcode-reader/downloads/) the xcframework and update the `vision-camera-dynamsoft-barcode-reader.podspec` file to use it.

```diff
- s.dependency 'DynamsoftBarcodeReader', '= 9.0.2'
+ s.vendored_frameworks = 'DynamsoftBarcodeReader.xcframework'
```

If you have further questions, please contact [support@dynamsoft.com](mailto:support@dynamsoft.com).

**Comment by Nass30** [comment]
Worked on Simulator, but no more on the device.

I just updated the DynamsoftBarcodeReader pod version to 9.2.12 and it's worked on both. I just need to check if there are no breaking changes. Do you plan to update it too?

**Comment by xulihang** [comment]
Ok. I will update it.

**Comment by xulihang** [comment]
I've updated it to 9.2.

**Comment by saravanaS2108** [comment]
Still facing the same issue in IOS.

**Comment by ajiehatajie** [comment]
same issue build in simulator with react native 0.70 
but build in physical device is working


Showing All Errors Only
Building for iOS Simulator, but linking in dylib built for iOS, file 'food-app/ios/Pods/DynamsoftBarcodeReader/DynamsoftBarcodeReader.framework/DynamsoftBarcodeReader' for architecture arm64

**Comment by ManAnRuck** [comment]
Same issue with `DynamsoftBarcodeReader (9.2.12)`

vision-camera-dynamsoft-barcode-reader 0.4.4
react native 0.70.4

**Comment by Hopefulee** [comment]
Have similar issue that i cannot do `arch -x86_64 pod install` for ios with M1 mac, it says `(mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))` for me. 


    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-vision-camera": "2.12.0"

Anyone found a solution?

**Comment by xulihang** [comment]
The framework should work on iOS simulator on Intel or Apple CPUs.

If it does not work, you can use the following setting:

![image](https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/assets/5462205/ce88c231-b26e-4f85-9d7d-c6c3adc7fdce)
