### ISSUE TITLE
SwiftEmitModule build commands failed

### ISSUE THREAD

**Issue by mbritton** [xulihang/vision-camera-dynamsoft-barcode-reader#8]
React Native Version: 0.70.1
iOS min. deployment: 13.4
XCode: 14.0.1
Simulator: iPhone 12 Pro
Development System: Mac M1

I'm having trouble interpreting the following build error:

`The following build commands failed:
	SwiftEmitModule normal x86_64 Emitting\ module\ for\ vision_camera_dynamsoft_barcode_reader (in target 'vision-camera-dynamsoft-barcode-reader' from project 'Pods')
(1 failure)`

Not sure if relevant, but this error is happening after a Firebase SDK integration.

**Comment by tony-xlh** [comment]
I haven't encountered such an error. Maybe it is related to this issue: https://github.com/tony-xlh/vision-camera-dynamsoft-barcode-reader/issues/7

**Comment by mbritton** [comment]
We're trying version 14 of react-native-firebase, which installed without the aforementioned error, as a workaround.
