### ISSUE TITLE
How to add timeout between each scan?

### ISSUE THREAD

**Issue by aminvb12** [xulihang/vision-camera-dynamsoft-barcode-reader#9]
I was wondering how we can add timeout between each scan.

**Comment by xulihang** [comment]
You can add a timeout setting to the template:

```ts
const config:DBRConfig = {};
config.template="{\"ImageParameter\":{\"BarcodeFormatIds\":[\"BF_ALL\"],\"Description\":\"\",\"Timeout\": 3500, \"Name\":\"Settings\"},\"Version\":\"3.0\"}"; 
```

**Comment by aminvb12** [comment]
Thanks, in advance @xulihang 
Would you please provide me an example in order to how we can enable and disable scanner?

**Comment by xulihang** [comment]
What do you mean? 

Do you need to turn off the camera or turn off the frame processor?

If you only need to stop scanning, you can use a sharedValue of react-native-animated to control whether to call the decode function.

**Comment by aminvb12** [comment]
> What do you mean?
> 
> Do you need to turn off the camera or turn off the frame processor?
> 
> If you only need to stop scanning, you can use a sharedValue of react-native-animated to control whether to call the decode function.

@xulihang Thanks for your response.
Basically, I want to enable/disable frame processor between each successful scan for couple of seconds.

Would it be feasible for you, in order to provide me an example for it?
I would appreciate it Dear @xulihang

**Comment by CodingWithNobody** [comment]
Try this https://www.youtube.com/watch?v=sE0MEyFA7E4&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=7 & https://www.youtube.com/watch?v=BFkIIIKgjnE&list=PLQhQEGkwKZUrempLnmxjt7ZCZJu1W3p2i&index=80
